language: android
jdk: openjdk11

before_install:
  - sudo curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get -y install dpkg
  - sudo apt-get -y install bellsoft-java11

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.2
    - android-29
    - extra
    - extra-android-m2repository

script:
  - ./gradlew check javadoc confidence-android:jacocoTestReport

# upload JaCoCo report to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
